spring:
  application:
    name: flowable
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: flowable12345
server:
  port: 8080
flowable:
  mail:
    server:
      host: smtp.163.com
      port: 25
      username: xxx
      password: xxx
      default-from: xxx
  common:
    app:
      idm-url: http://localhost:8080
      idm-admin:
        user: admin
        password: admin
  database-schema-update: true
  admin:
    app:
      security:
        encryption:
          credentials-i-v-spec: ajdklflsl2k3dl2l
          credentials-secret-spec: f4e2e52034348f86b67cde581c0f9eb5
